version: '3.8'

services:
  db:
    image: postgres:15
    container_name: innova-db
    restart: always
    environment:
      POSTGRES_DB: db_innovasolutions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432" # Regresado al estándar para AWS
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
