version: '3.8'

services:
  db:
    image: postgres:15
    container_name: innova-db
    restart: always
    environment:
      POSTGRES_DB: db_innovasolutions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432" # Regresado al estándar para AWS/Ubuntu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - innova-network

  app:
    build: .
    container_name: innova-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_innovasolutions
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgre
      - JWT_SECRET=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==
      - IP_FRONTEND=http://localhost:4200
    networks:
      - innova-network

networks:
  innova-network:
    driver: bridge

volumes:
  postgres_data:
