spring.application.name=Innova-Solutions-Backend

# Configuración de base de datos (Usando variables de entorno con valores por defecto)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_innovasolutions}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:josue123}
# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ejecución de import.sql
spring.sql.init.mode=always

# Seguridad y JWT
ip.frontend=${IP_FRONTEND:http://localhost:4200}
jwt.secret=${JWT_SECRET:0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==}

# Errores
server.error.include-stacktrace=never